services:
  billing:
    image: billing
    build:
      context: .
      dockerfile: Billing/Dockerfile

  billing.api:
    image: billing.api
    build:
      context: .
      dockerfile: src/backend/Services/Billing.API/Dockerfile

  integration.services:
    image: integration.services
    build:
      context: .
      dockerfile: src/backend/src/Workers/Integration.Services/Dockerfile

