services:

  # ---------------------
  # --- Secrets ---
  # ---------------------
  vault:
    image: vault:1.13.0
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: dev-token
    command: server -dev
    depends_on:
      billing-postgres:
        condition: service_healthy
    networks:
      - billing-net

  # ---------------------
  # --- Discovery ---
  # ---------------------
  consul:
    image: hashicorp/consul # Imagen oficial de Consul
    container_name: consul
    command: "agent -dev -client=0.0.0.0"
    ports:
      - "${CONSUL_PORT}:8500"   # Puerto para la interfaz web y API HTTP
      - "8600:8600/udp"         # Puerto para consultas DNS
    healthcheck:
      test: [ "CMD", "curl", "-f", "${CONSUL_URL}" ]
      interval: "10s"
      timeout: "5s"
      retries: 5
    networks:
      - observability
      - billing-net

  # ---------------------
  # --- RabbitMQ ---
  # ---------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: billing-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - billing-net

  # ---------------------
  # --- Cache ---
  # ---------------------

  distributedcache:
    image: redis:latest
    container_name: distributedcache
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - billing-net

  # ---------------------
  # --- Observability ---
  # ---------------------
  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: alpine:3.19
    container_name: init
    user: root
    entrypoint: [ "sh", "-c", "chown -R 10001:10001 /var/tempo" ]
    volumes:
      - tempo-data:/var/tempo

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    restart: unless-stopped
    ports:
      - "3200:3200"
      - "4317:4317"
    volumes:
      - ../tools/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    depends_on:
      - init
    networks:
      - observability
      - billing-net

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ../tools/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    ports:
      - "${LOKI_PORT}:3100"
    networks:
      - observability

  alloy:
    image: grafana/alloy:v1.3.1
    container_name: alloy
    volumes:
      - ../tools/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock:ro  # <--- ¡Asegura el acceso al socket!
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"
      - "4318:4318"
    depends_on:
      - tempo
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT}:9090"
    volumes:
      - ../tools/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    depends_on:
      - loki
    networks:
      - observability
      - billing-net

  grafana:
    image: grafana/grafana:12.0.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ../tools/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
      - loki
      - tempo
    networks:
      - observability
      - billing-net

  # ---------------------
  # --- Database      ---
  # ---------------------
  billing-postgres:
    image: postgres:15
    container_name: billing-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: billingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: "10s"
      timeout: "5s"
      retries: 5
    networks:
      - billing-net

  eventrelay-postgres:
    image: postgres:15
    container_name: eventrelay-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: eventrelaylogdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: "10s"
      timeout: "5s"
      retries: 5
    networks:
      - billing-net

  # ---------------------
  # --- Services      ---
  # ---------------------

  billing.api:
    build:
      context: ../../src/backend   # ← Esto debe apuntar a D:\Repositorio\Billing
      dockerfile: src/Services/Billing.API/Dockerfile
    container_name: billing.api
    ports:
      - "6000:8080"
      - "6060:8081"
    environment:
      ConnectionStrings__Database: "Server=billing-postgres;Port=5432;Database=billingdb;User Id=postgres;Password=postgres;Include Error Detail=true"
      DatabaseConfig__Server: billing-postgres
      DatabaseConfig__Port: 5432
      DatabaseConfig__Database: billingdb
      MessageBroker__Host: billing-mq
      MessageBroker__Username: guest
      MessageBroker__Password: guest
      ConsulConfig__ServiceId: "billing.api-1"
      ConsulConfig__ServiceName: "billing.api"
      ConsulConfig__ServiceAddress: "billing.api"
      ConsulConfig__ServicePort: 8080
      ConsulConfig__HealthCheckUrl: "http://billing.api:8080/health"
      ConsulConfig__Host: "http://consul:8500"
      ConsulConfig__TLSSkipVerify: false
      logging__Service: "app"
      logging__ServiceName: "BILLING.api"
      logging__LokiUrl: "http://loki:3100/loki/api/v1/push"
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: dev-token
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6000/health" ]
      interval: "30s"
      timeout: "10s"
      retries: 5
    depends_on:
      - consul
      - vault
      - rabbitmq
      - billing-postgres
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - billing-net

  #  eventrelay:
  #    build:
  #      context: ../../src/backend
  #      dockerfile: src/Workers/Integration.Services/Dockerfile
  #    container_name: eventrelay
  #    depends_on:
  #      messagebroker:
  #        condition: service_healthy
  #    environment:
  #      ConnectionStrings__Database: "Server=${EVT_POSTGRES_HOST};Port=${EVT_POSTGRES_PORT};Database=${EVT_POSTGRES_DB};Username=${EVT_POSTGRES_USER};Password=${EVT_POSTGRES_PASSWORD};Include Error Detail=true"
  #      MessageBroker__Host: ${RABBITMQ_HOST}
  #      MessageBroker__Username: ${RABBITMQ_USER}
  #      MessageBroker__Password: ${RABBITMQ_PASSWORD}
  #    networks:
  #      - billing-net


  # ---------------------
  # --- Gateway      ---
  # ---------------------

  #yarpapigateway:
  #  container_name: yarpapigateway
  #  build:
  #    context: ../../src/backend   # ← Esto debe apuntar a D:\Repositorio\Axenta
  #    dockerfile: src/ApiGateways/YarpApiGateway/Dockerfile
  #  environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  #    - ASPNETCORE_HTTP_PORTS=8080
  #    #- ASPNETCORE_HTTPS_PORTS=8081
  #  depends_on:
  #    - billing.api
  #  ports:
  #    - "6009:8080"
  #    #- "6069:8081"
  #  volumes:
  #    - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
  #    - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  #  networks:
  #    - billing-net

volumes:
  grafana_data:
  prometheus-data:
  tempo-data:
  loki-data:

networks:
  observability:
    driver: bridge
  billing-net:
    driver: bridge