<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Abstractions\Interfaces\"/>
        <Folder Include="Abstractions\Services\"/>
        <Folder Include="Features\Invoices\EventHandlers\Integration\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\shared\BuildingBlocks.Messaging\BuildingBlocks.Messaging.csproj"/>
        <ProjectReference Include="..\..\shared\BuildingBlocks\BuildingBlocks.csproj"/>
        <ProjectReference Include="..\Billing.Domain\Billing.Domain.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7"/>
        <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="4.4.0"/>
    </ItemGroup>

</Project>
