services:
  - name: billing-db
    type: postgres
    internal_host: billing-postgres
    external_host: localhost
    port: 5432

  - name: event-db
    type: postgres
    internal_host: event-postgres
    external_host: localhost
    port: 5433

  - name: rabbitmq
    type: rabbitmq
    internal_host: billing-mq
    external_host: localhost
    port: 5672
    management_port: 15672
    user: guest
    password: guest