services:

  - name: billing-db
    type: postgres

    connection:
      internal_host: billing-postgres   # Docker
      external_host: localhost          # Host machine
      port: 5432
      database: billingdb
      admin_user: postgres
      admin_password: postgres

    consul:
      enabled: true
      service_name: billing-postgres

    vault:
      enabled: true

      engine: database
      connection_name: billing-db

      roles:
        - name: billing-role
          ttl: 1h
          max_ttl: 24h

          permissions:
            - SELECT
            - INSERT
            - UPDATE
            - DELETE

  - name: event-db
    type: postgres

    connection:
      internal_host: eventrelay-postgres   # Docker
      external_host: localhost             # Host machine
      port: 5432
      database: eventrelaylogdb
      admin_user: postgres
      admin_password: postgres

    consul:
      enabled: true
      service_name: eventrelay-postgres

    vault:
      enabled: true
      engine: database
      connection_name: event-db

      roles:
        - name: event-role
          ttl: 1h
          max_ttl: 24h

          permissions:
            - read
            - write

  - name: rabbitmq
    type: rabbitmq

    connection:
      internal_host: billing-mq      #  docker
      external_host: localhost       #  host
      port: 5672
      management_port: 15672
      admin_user: guest
      admin_password: guest

    vault:
      enabled: true
      engine: rabbitmq

      roles:
        - name: rabbit-role
          tags: administrator

          vhosts:
            "/":
              configure: ".*"
              write: ".*"
              read: ".*"

  - name: billing.api
    type: http
    url: http://localhost:6000/health

  - name: Integration.Services
    type: worker
    command:
      - dotnet
      - Integration.Services.dll