receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
# loki:
#   endpoint: "http://loki:3100/loki/api/v1/push"
  otlp:
    endpoint: "tempo:4317"
    tls:
      insecure: true

processors:
  batch:

service:

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
 #  logs:
 #    receivers: [otlp]
 #    processors: [batch]
 #    exporters: [loki]

extensions:
  health_check: