apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET

  - uid: tempo
    orgId: 1
    name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
        filterByTraceID: true
        tags:
          - key: service.name
            value: service_name
      serviceMap:
        datasourceUid: prometheus     # ✅ de dónde lee el grafo
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: prometheus
    editable: true

  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherType: label          # ← usa structured metadata, no regex
          name: trace_id
          url: '$${__value.raw}'
          urlDisplayLabel: 'Ver traza'
    editable: true