groups:
  - name: microservices-alerts
    rules:

      - alert: HighErrorRate
        expr: rate(http_server_requests_total{status_code=~"5.."}[2m]) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Alta tasa de errores"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_server_request_duration_seconds_bucket[2m])) > 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Latencia alta"